version: "3.8"

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "2000:2000"
    env_file:
      - ./services/frontend/.env.dev
    networks:
      - default
    stdin_open: true

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./services/backend/:/src
    ports:
      - "8004:8004"
    env_file:
      - ./services/backend/.env.dev
    depends_on:
      - db
    networks:
      - default

  evm-contracts:
    build:
      context: ./services/evm-contracts
      dockerfile: Dockerfile
    restart: always
    container_name: evm-contracts
    volumes:
      - ./services/evm-contracts:/app
      - /app/node_modules
      - /app/artifacts
      - /app/cache
      - /app/typechain-types
    ports:
      - "8545:8545"
    env_file:
      - ./services/evm-contracts/.env.dev
    networks:
      - default
    stdin_open: true

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./services/db/.env.dev
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
