import Head from "next/head";
import { Button } from "@taikai/rocket-kit";
import { useWeb3 } from "../hooks/useWeb3";
import { Container, Main, NavBar, BrandName, Menu , Footer, Title, SubTitle, Content}  from "../styles/home";
import ConnectModal from "../components/connect-wallet-modal";
import React, { useState } from 'react';
import ClickableEthAddress  from "../components/clickable-eth-address";
import Image from "next/image";
import logo from "../public/fundec-ico.png"

export default function Home() {

  const { connected } = useWeb3();
  const [isConnectModal, setConnectModal] = useState(false);
  return (
    <Container>
      <Head>
        <title>FundEC DApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/fundec-ico.ico" />
      </Head>
      <NavBar>
        <BrandName> <Image src={logo} width={55} alt="fundec" /></BrandName>

        <Menu>
          {!connected && (
            <Button
              ariaLabel="Connect"
              className="button"
              color="green"
              value="Connect"
              variant="solid"
              action={()=> setConnectModal(true)}
            />
          )}
          {connected && <ClickableEthAddress onClick={()=> setConnectModal(true)}/>}
        </Menu>
      </NavBar>
      {isConnectModal && <ConnectModal onClose={()=> setConnectModal(false)}/>}
      <Main>
        <Content>
          <Title>FundEC - Invest Locally, Impact Globally</Title>
          <SubTitle>Crowdlending for sustainable projects based on 
            &nbsp;<strong style={{color: "#222", textStyle: 'italic'}}>Dappkit</strong>™ + 
            <strong style={{color: "#222"}}>RocketKit</strong>™&nbsp;  🙌
          </SubTitle>
        </Content>        
      </Main>
      <Footer>Made with ❤️ by <strong>FundEC</strong> - 2023</Footer>
    </Container>
  );
}
